version: "2"

services:
  app:
    build: .docker/app/
    ports:
      - 80:80
    working_dir: /var/www
    volumes:
      - .:/var/www
      - .docker/app/default.conf:/etc/apache2/sites-available/000-default.conf
      - .docker/app/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - "database"

  database:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: application
    volumes:
      - .docker/database/application.sql:/docker-entrypoint-initdb.d/application.sql

  dbadmin:
    image: adminer
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=database
      - ADMINER_DEFAULT_USER=root
    depends_on:
      - "database"